name: chill_map
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.18.0+1
  google_maps_flutter: ^0.5.28
  google_maps_flutter_web: ^0.1.0+2
  responsive_builder: ^0.3.0
  google_sign_in: ^4.5.4
  googleapis_auth: 0.2.10
  flutter_signin_button: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - lib/resources/icon.png
  - web/icons/Icon-192.png
  - web/icons/Icon-512.png